"""configure *only* the banking API's three telemetry signals.

Telemetry is opt-in (OTEL_ENABLED=true). All exporters send to internal Alloy.
Avoid logging request bodies, raw paths, HTTP headers, SQL parameters or exceptions.
"""

import logging
import os
import re
import time
from uuid import uuid4

from fastapi import Request
from opentelemetry import metrics, trace
from opentelemetry._logs import set_logger_provider
from opentelemetry.exporter.otlp.proto.http._log_exporter import OTLPLogExporter
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.psycopg import PsycopgInstrumentor
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

# Request IDs are generated by the server, never accepted blindly from users.
# Lower cardinality HTTP route templates (not /accounts/<uuid>) are safe for metrics.
SERVICE_NAME = os.getenv("OTEL_SERVICE_NAME", "synthetic-banking-api")
ENABLED = os.getenv("OTEL_ENABLED", "false").lower() == "true"
OTLP_BASE = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://alloy:4318").rstrip("/")

_logger = logging.getLogger("banking.observability")
_request_count = None
_request_duration = None
_payment_count = None


def configure_telemetry():
    """Call exactly once, before constructing/instrumenting the FastAPI app."""
    global _request_count, _request_duration, _payment_count
    if not ENABLED:
        return

    resource = Resource.create({"service.name": SERVICE_NAME, "deployment.environment.name": "local-lab"})

    # Traces: 1 API request span with child PostgreSQL spans. Never add SQL arguments.
    tracer_provider = TracerProvider(resource=resource)
    tracer_provider.add_span_processor(BatchSpanProcessor(
        OTLPSpanExporter(endpoint=f"{OTLP_BASE}/v1/traces", timeout=5)
    ))
    trace.set_tracer_provider(tracer_provider)
    PsycopgInstrumentor().instrument()

    # Metrics: cumulative low-cardinality counters + histogram; no account IDs.
    metrics_provider = MeterProvider(
        resource=resource,
        metric_readers=[PeriodicExportingMetricReader(
            OTLPMetricExporter(endpoint=f"{OTLP_BASE}/v1/metrics", timeout=5),
            export_interval_millis=10000,
        )],
    )
    metrics.set_meter_provider(metrics_provider)
    meter = metrics.get_meter("banking-api")
    _request_count = meter.create_counter("banking.api.requests", unit="{request}")
    _request_duration = meter.create_histogram("banking.api.duration", unit="s")
    _payment_count = meter.create_counter("banking.payment.requests", unit="{request}")

    # Logs: attach an exporter to ONE dedicated, allowlisted logger only.
    # Do not attach to root: framework/DB logs can contain unsafe exception details.
    logger_provider = LoggerProvider(resource=resource)
    logger_provider.add_log_record_processor(BatchLogRecordProcessor(
        OTLPLogExporter(endpoint=f"{OTLP_BASE}/v1/logs", timeout=5)
    ))
    set_logger_provider(logger_provider)
    _logger.setLevel(logging.INFO)
    _logger.propagate = False
    _logger.addHandler(LoggingHandler(level=logging.INFO, logger_provider=logger_provider))


def instrument_api(app):
    """Add FastAPI spans after registering ordinary app middleware/routers."""
    if ENABLED:
        FastAPIInstrumentor.instrument_app(
            app,
            excluded_urls="/health,/docs,/openapi.json,/redoc",
            exclude_spans=["receive", "send"],
        )


async def telemetry_middleware(request: Request, call_next):
    """Capture safe metadata once per request, including failures.

    Never place a correlation ID on metric labels. HTTP route templates are
    discovered *after* routing so a customer/account UUID is never a label.
    """
    if not ENABLED:
        return await call_next(request)

    started = time.monotonic()
    correlation_id = uuid4().hex
    span = trace.get_current_span()
    if span.is_recording():
        span.set_attribute("banking.correlation_id", correlation_id)

    try:
        response = await call_next(request)
        status_code = response.status_code
    except Exception:
        # Avoid exception text: it may contain SQL details or user input.
        status_code = 500
        _record(request, correlation_id, status_code, time.monotonic() - started)
        raise

    response.headers["X-Correlation-ID"] = correlation_id
    _record(request, correlation_id, status_code, time.monotonic() - started)
    return response


def _record(request, correlation_id, status_code, elapsed):
    """Aggregate by *template* and status; log per-request IDs separately."""
    route = request.scope.get("route")
    route_template = getattr(route, "path", "UNMATCHED")
    # Defense in depth: no arbitrary route path can become a telemetry field.
    if not isinstance(route_template, str) or not re.fullmatch(r"[/{}a-zA-Z0-9_-]{1,120}", route_template):
        route_template = "UNMATCHED"
    method = request.method if request.method in {"GET", "POST", "PUT", "PATCH", "DELETE"} else "OTHER"
    attrs = {"http_route": route_template, "http_method": method, "http_status": str(status_code)}
    _request_count.add(1, attrs)
    _request_duration.record(elapsed, attrs)

    # Count outcomes by HTTP status only. Do not inspect a response body, which
    # might contain protected payment or identity data.
    if route_template == "/api/v1/payments" and method == "POST":
        _payment_count.add(1, {"http_status": str(status_code)})

    current_span = trace.get_current_span()
    ctx = current_span.get_span_context()
    trace_id = format(ctx.trace_id, "032x") if ctx.is_valid else ""
    _logger.info("api_request_completed", extra={
        "correlation_id": correlation_id,
        "trace_id": trace_id,
        "http_route": route_template,
        "http_method": method,
        "http_status": status_code,
        "duration_ms": round(elapsed * 1000, 2),
    })
